// Only HTML generated by our escaped table renderer can bypass template escaping.
const htmlFunctions = new WeakSet<Function>();

export function registerHtmlFunction<T extends Function>(fn: T): T {
  htmlFunctions.add(fn);
  return fn;
}

export function isHtmlFunction(value: unknown): value is (...args: unknown[]) => string {
  return typeof value === 'function' && htmlFunctions.has(value);
}

export function escapeHtml(text: string): string {
  return text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;').replaceAll("'", '&#39;');
}
