#!/usr/bin/env node
/// <reference types="node" />
/**
 * i18n-gen.ts — Build-time translation generator.
 *
 * Reads `<root>/i18n.config.ts`, merges YAML files, and emits typed TypeScript.
 *
 * Run:  npx tsx i18n-gen.ts [project-root]
 * Deps: js-yaml  →  npm i -D js-yaml @types/js-yaml
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { join, resolve } from 'path'
import { pathToFileURL } from 'url'
import { load as parseYaml } from 'js-yaml'

// ─── Public types ────────────────────────────────────────────────────────────

/**
 * Shape of the default export in `i18n.config.ts`.
 * Import this type in your config file for autocompletion.
 *
 * @example
 * import type { I18nConfig } from './i18n-gen'
 * export default { ... } satisfies I18nConfig
 */
export interface I18nConfig {
  /** All supported BCP-47 language tags, e.g. `['en', 'zh-CN']`. */
  languages: string[]

  /**
   * Fallback language used when a key has no translation for the requested lang.
   * @default languages[0]
   */
  defaultLang?: string

  /**
   * YAML source files relative to the project root.
   * Keys in later files overwrite earlier ones.
   */
  files: string[]

  output: {
    /**
     * `'single'`   → one `<filename>.ts` with a named const export per language.
     * `'multiple'` → one `<langId>.ts` per language + a barrel `index.ts`.
     */
    mode: 'single' | 'multiple'

    /** Output directory relative to the project root. */
    dir: string

    /**
     * Base filename (no extension) for single-mode output.
     * @default 'translations'
     */
    filename?: string
  }
}

// ─── Internal types ──────────────────────────────────────────────────────────

/** Raw YAML document shape. String values are language-neutral. */
type YamlDoc = Record<string, string | Record<string, string>>

/** Flat `{ key: translatedString }` dictionary for one language. */
type Dict = Record<string, string>

/** All translations keyed by language tag. */
type Translations = Record<string, Dict>

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Convert a language tag to a valid JS identifier: `'zh-CN'` → `'zhCN'`. */
function toId(lang: string): string {
  return lang.replace(/[-_]([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase())
}

// ─── Core logic ───────────────────────────────────────────────────────────────

/**
 * Merge all YAML files into per-language flat dictionaries.
 *
 * - A plain string value is shared across every language as-is.
 * - An object value selects the string for each language tag.
 *   Missing tags fall back to `fallbackLang`, then the first available value.
 */
function buildTranslations(
  files: string[],
  languages: string[],
  root: string,
  fallbackLang: string,
): Translations {
  const out: Translations = Object.fromEntries(languages.map(l => [l, {} as Dict]))

  for (const rel of files) {
    const abs = resolve(root, rel)
    if (!existsSync(abs)) {
      console.warn(`[i18n-gen] Skipping missing file: ${abs}`)
      continue
    }

    const doc = parseYaml(readFileSync(abs, 'utf-8')) as YamlDoc

    for (const [key, value] of Object.entries(doc)) {
      if (typeof value === 'string') {
        for (const lang of languages) out[lang][key] = value
      } else {
        for (const lang of languages) {
          out[lang][key] =
            value[lang]                 // exact match
            ?? value[fallbackLang]      // fallback language
            ?? Object.values(value)[0]  // first available translation
            ?? key                      // bare key as last resort
        }
      }
    }
  }

  return out
}

// ─── Renderers ────────────────────────────────────────────────────────────────

const BANNER = '// Auto-generated by i18n-gen. Do not edit manually.\n'

/**
 * Single-file mode: all languages as named const exports in one file.
 *
 * @example output
 * export const en = { greeting: "Hello" } as const
 * export const zhCN = { greeting: "你好" } as const
 * export type Lang = 'en' | 'zh-CN'
 * export type TranslationKey = keyof typeof en
 */
function renderSingle(translations: Translations, languages: string[]): string {
  const parts: string[] = [BANNER]

  for (const lang of languages) {
    parts.push(
      `export const ${toId(lang)} = ${JSON.stringify(translations[lang], null, 2)} as const\n`,
    )
  }

  parts.push(`export type Lang = ${languages.map(l => `'${l}'`).join(' | ')}`)
  parts.push(`export type TranslationKey = keyof typeof ${toId(languages[0])}`)

  return parts.join('\n')
}

/** Multiple-file mode: one default-export file per language. */
function renderLangFile(dict: Dict): string {
  return `${BANNER}\nexport default ${JSON.stringify(dict, null, 2)} as const\n`
}

/**
 * Barrel index for multiple-file mode.
 *
 * @example output
 * export { default as en } from './en'
 * export { default as zhCN } from './zhCN'
 * export type Lang = 'en' | 'zh-CN'
 * export type TranslationKey = keyof _Base  // keyed off first language
 */
function renderIndex(languages: string[]): string {
  const lines: string[] = [BANNER]

  for (const lang of languages)
    lines.push(`export { default as ${toId(lang)} } from './${toId(lang)}'`)

  lines.push('')
  lines.push(`export type Lang = ${languages.map(l => `'${l}'`).join(' | ')}`)
  lines.push(`import type _Base from './${toId(languages[0])}'`)
  lines.push(`export type TranslationKey = keyof _Base`)

  return lines.join('\n')
}

// ─── Entry point ──────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const root = resolve(process.argv[2] ?? process.cwd())
  const configPath = join(root, 'i18n.config.ts')

  if (!existsSync(configPath)) {
    console.error(`[i18n-gen] Config not found: ${configPath}`)
    process.exit(1)
  }

  const mod = await import(pathToFileURL(configPath).href)
  const config: I18nConfig = mod.default ?? mod

  if (!config.languages.length) {
    console.error('[i18n-gen] `languages` array is empty.')
    process.exit(1)
  }

  const defaultLang = config.defaultLang ?? config.languages[0]
  const translations = buildTranslations(config.files, config.languages, root, defaultLang)

  const outDir = resolve(root, config.output.dir)
  mkdirSync(outDir, { recursive: true })

  const write = (path: string, content: string) => {
    writeFileSync(path, content, 'utf-8')
    console.log(`[i18n-gen] ✓ ${path}`)
  }

  if (config.output.mode === 'single') {
    const name = config.output.filename ?? 'translations'
    write(join(outDir, `${name}.ts`), renderSingle(translations, config.languages))
  } else {
    for (const lang of config.languages)
      write(join(outDir, `${toId(lang)}.ts`), renderLangFile(translations[lang]))

    write(join(outDir, 'index.ts'), renderIndex(config.languages))
  }
}

main().catch(err => {
  console.error('[i18n-gen]', err)
  process.exit(1)
})